@startuml
class Produto{
    - nome: str
    - preco: float
    - quantidade: int 
}

class Software {
    - licenca: str
}

class Hardware{
    - garantia: int
}


left to right direction

Produto <-- (Software, Hardware)

@enduml 